{% set name = "searoute" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/searoute-{{ version }}.tar.gz
  sha256: 0d7f302503869b304f92c5ca6c53497934d412f60b759e1f3615b4cdc1680751

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - geojson
    - networkx

test:
  imports:
    - searoute
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/searoute/
  summary: A python package for generating the shortest sea route between two points on Earth.
  dev_url: https://github.com/genthalili/searoute-py
  license: MIT
  license_file: LICENCE.txt

extra:
  recipe-maintainers:
    - vinisalazar
